// src/utils/assets.ts

// 1. ใส่ path ของรูปที่ไฟล์ใหญ่ๆ หรือรูปที่อยู่ใน Scene แรกๆ ลงในนี้
// ยิ่งใส่ครบ หน้าเว็บยิ่งลื่น แต่หน้าโหลดก็จะนานขึ้นนิดนึงตามขนาดไฟล์
export const ASSETS_TO_PRELOAD = [
  // Hero Scene
  "/assets/Scene/Hero/hill-c-b.svg",
  "/assets/Scene/Hero/hill-c-f.svg",
  "/assets/Scene/Hero/hill-l-f.svg",
  "/assets/Scene/Hero/hill-r-f.svg",
  "/assets/Scene/Hero/love-circle.svg",
  "/assets/Scene/Hero/skill-circle.svg",
  "/assets/Scene/Hero/world-circle.svg",
  "/assets/Scene/Hero/paid-circle.svg",

  // Intro Scene
  "/assets/Scene/Intro/bg.svg",
  "/assets/Scene/Intro/animal.svg",
  "/assets/Scene/Intro/desert1.svg",
  "/assets/Scene/Intro/desert2.svg",
  "/assets/Scene/Intro/desert3.svg",
  "/assets/Scene/Intro/sun.svg",

  // Scene1 (Job Application)
  "/assets/Scene/Scene1/table.svg",
  "/assets/Scene/Scene1/Computer.svg",
  "/assets/Scene/Scene1/window.svg",
  "/assets/Scene/Scene1/curtain1.svg",
  "/assets/Scene/Scene1/curtain2.svg",
  "/assets/Scene/Scene1/building1.svg",
  "/assets/Scene/Scene1/building2.svg",
  "/assets/Scene/Scene1/circle.svg",
  "/assets/Scene/Scene1/moon.svg",
  "/assets/Scene/Scene1/lamp.svg",
  "/assets/Scene/Scene1/book1.svg",
  "/assets/Scene/Scene1/book2.svg",
  "/assets/Scene/Scene1/paper1.svg",
  "/assets/Scene/Scene1/paper2.svg",
  "/assets/Scene/Scene1/paper3.svg",
  "/assets/Scene/Scene1/paper4.svg",
  "/assets/Scene/Scene1/pen.svg",
  "/assets/Scene/Scene1/pencil box.svg",
  "/assets/Scene/Scene1/postit.svg",
  "/assets/Scene/Scene1/light.svg",
  "/assets/Scene/Scene1/light window.svg",
  "/assets/Scene/Scene1/star.svg",
  "/assets/Scene/Scene1/poster1.svg",
  "/assets/Scene/Scene1/poster2.svg",
  "/assets/Scene/Scene1/poster3.svg",
  "/assets/Scene/Scene1/poster4.svg",
  "/assets/Scene/Scene1/poster5.svg",
  "/assets/Scene/Scene1/poster6.svg",
  "/assets/Scene/Scene1/poster7.svg",
  "/assets/Scene/Scene1/poster8.svg",
  "/assets/Scene/Scene1/poster9.svg",
  "/assets/Scene/Scene1/poster10.svg",
  "/assets/Scene/Scene1/poster11.svg",
  "/assets/Scene/Scene1/poster12.svg",
  "/assets/Scene/Scene1/poster13.svg",
  "/assets/Scene/Scene1/poster14.svg",
  "/assets/Scene/Scene1/poster15.svg",

  // Scene2 (Sleeping)
  "/assets/Scene/Scene2/bg.svg",
  "/assets/Scene/Scene2/bed.svg",
  "/assets/Scene/Scene2/table1.svg",
  "/assets/Scene/Scene2/table2.svg",
  "/assets/Scene/Scene2/lamp.svg",
  "/assets/Scene/Scene2/clock.svg",
  "/assets/Scene/Scene2/book1.svg",
  "/assets/Scene/Scene2/book2.svg",
  "/assets/Scene/Scene2/note.svg",
  "/assets/Scene/Scene2/head.svg",
  "/assets/Scene/Scene2/body.svg",
  "/assets/Scene/Scene2/blanket.svg",
  "/assets/Scene/Scene2/phone.svg",
  "/assets/Scene/Scene2/slipper.svg",

  // Scene4 (Weighing)
  "/assets/Scene/Scene4/bg.svg",
  "/assets/Scene/Scene4/sky.svg",
  "/assets/Scene/Scene4/wall.svg",
  "/assets/Scene/Scene4/ground.svg",
  "/assets/Scene/Scene4/pool.svg",
  "/assets/Scene/Scene4/stairs.svg",
  "/assets/Scene/Scene4/building.svg",
  "/assets/Scene/Scene4/treeleft.svg",
  "/assets/Scene/Scene4/treeright.svg",
  "/assets/Scene/Scene4/poleleft.svg",
  "/assets/Scene/Scene4/poleright.svg",
  "/assets/Scene/Scene4/catleft.svg",
  "/assets/Scene/Scene4/catright.svg",
  "/assets/Scene/Scene4/light.svg",
  "/assets/Scene/Scene4/scale.svg",
  "/assets/Scene/Scene4/scale-2.svg",
  "/assets/Scene/Scene4/scale-feather.svg",
  "/assets/Scene/Scene4/heart.svg",
  "/assets/Scene/Scene4/heart-scale.svg",
  "/assets/Scene/Scene4/heart-plate.svg",
  "/assets/Scene/Scene4/feather.svg",
  "/assets/Scene/Scene4/feather-plate.svg",
  "/assets/Scene/Scene4/night mode.svg",

  // Scene5-01 (Into Dark - Name Input)
  "/assets/Scene/Scene5/scene5-01/bggradient.svg",
  "/assets/Scene/Scene5/scene5-01/Light cat.svg",
  "/assets/Scene/Scene5/scene5-01/Little star1.svg",
  "/assets/Scene/Scene5/scene5-01/Little star2.svg",
  "/assets/Scene/Scene5/scene5-01/Little star3.svg",
  "/assets/Scene/Scene5/scene5-01/star line1.svg",
  "/assets/Scene/Scene5/scene5-01/star line2.svg",
  "/assets/Scene/Scene5/scene5-01/star line3.svg",
  "/assets/Scene/Scene5/scene5-01/water.svg",
  "/assets/Scene/Scene5/scene5-01/tail.svg",
  "/assets/Scene/Scene5/scene5-01/cat face.svg",

  // Scene5-02 (Into Dark - Choices)
  "/assets/Scene/Scene5/scene5-02/bggradient1.svg",
  "/assets/Scene/Scene5/scene5-02/bggradient2.svg",
  "/assets/Scene/Scene5/scene5-02/bggradient3.svg",
  "/assets/Scene/Scene5/scene5-02/Light Cat.svg",
  "/assets/Scene/Scene5/scene5-02/cat.svg",
  "/assets/Scene/Scene5/scene5-02/cat face.svg",
  "/assets/Scene/Scene5/scene5-02/Little Star1.svg",
  "/assets/Scene/Scene5/scene5-02/Little Star2.svg",
  "/assets/Scene/Scene5/scene5-02/Little Star3.svg",
  "/assets/Scene/Scene5/scene5-02/Star line1.svg",
  "/assets/Scene/Scene5/scene5-02/Star line2.svg",

  // Scene5-03 (Into Dark - Heard)
  "/assets/Scene/Scene5/scene5-03/bggradient.svg",
  "/assets/Scene/Scene5/scene5-03/Light Cat.svg",
  "/assets/Scene/Scene5/scene5-03/Cloud.svg",
  "/assets/Scene/Scene5/scene5-03/Little Star1.svg",
  "/assets/Scene/Scene5/scene5-03/Little Star2.svg",
  "/assets/Scene/Scene5/scene5-03/Little Star3.svg",
  "/assets/Scene/Scene5/scene5-03/Star line1.svg",

  // Scene5-04 (Into Dark - Submit)
  "/assets/Scene/Scene5/scene5-04/bggradient1.svg",
  "/assets/Scene/Scene5/scene5-04/bggradient2.svg",
  "/assets/Scene/Scene5/scene5-04/Cloud1.svg",
  "/assets/Scene/Scene5/scene5-04/Cloud2.svg",
  "/assets/Scene/Scene5/scene5-04/Light Cat.svg",
  "/assets/Scene/Scene5/scene5-04/Line star1.svg",
  "/assets/Scene/Scene5/scene5-04/Little star.svg",
  "/assets/Scene/Scene5/scene5-04/Little star1.svg",
  "/assets/Scene/Scene5/scene5-04/Little star1-1.svg",
  "/assets/Scene/Scene5/scene5-04/Little star2.svg",
  "/assets/Scene/Scene5/scene5-04/Little star2-1.svg",
  "/assets/Scene/Scene5/scene5-04/love circle.svg",
  "/assets/Scene/Scene5/scene5-04/paid circle.svg",
  "/assets/Scene/Scene5/scene5-04/skill circle.svg",
  "/assets/Scene/Scene5/scene5-04/world circle.svg",
  "/assets/Scene/Scene5/scene5-04/cat.svg",
  "/assets/Scene/Scene5/scene5-04/cat face.svg",
  "/assets/Scene/Scene5/scene5-04/cat-noise.svg",
];

// ฟังก์ชันช่วยเรียก URL (เผื่ออนาคตอยากกลับไปใช้ CDN ก็แก้ที่นี่ที่เดียว)
export const getAssetUrl = (path: string): string => {
  // ถ้าไม่ได้ตั้งค่า CDN ก็ให้คืนค่า path เดิม (ใช้ของ Vercel)
  const cdnBase = process.env.NEXT_PUBLIC_CDN_URL || "";
  const cleanPath = path.startsWith("/") ? path.slice(1) : path;
  return cdnBase ? `${cdnBase}/${cleanPath}` : `/${cleanPath}`;
};
